### PR TITLE
Add support for netstandard2.0 and new csproj format

### PR DESCRIPTION
**Pull request by wieslawsoltes**
This PR does the following changes:
* Converted csproj to new project format introduced in `Visual Studio 2017`
* New project format adds support for `netstandard2.0`, full `.NET Framework` and `.NET Core 2.0`
* AssemblyInfo is generated automatically using csproj (Removed Properties/AssemblyInfo.cs)
* Easily generate `*.nupkg` package during build
* Maintains compatibility with old framework targets and mono (using mono latest versions)

The `AssemblyInfo` and `NuGet` `nuspec` file  properties are all included in csproj file:
```
<PropertyGroup>
  <Version>1.0.0.0</Version>
  <Authors>Ryan Schmidt/gradientspace</Authors>
  <Company>Ryan Schmidt/gradientspace</Company>
  <Description>C# library for 3D geometric computation, mesh algorithms, etc.</Description>
  <Copyright>Copyright © Ryan Schmidt/gradientspace 2016</Copyright>
  <PackageLicenseUrl>https://github.com/gradientspace/geometry3Sharp/blob/master/LICENSE</PackageLicenseUrl>
  <PackageProjectUrl>https://github.com/gradientspace/geometry3Sharp</PackageProjectUrl>
  <PackageTags>geometry3;graphics;math;approximation;solvers;color;convexhull;meshes;spatial;curves;solids;3d;unity</PackageTags>
</PropertyGroup>
```

Example building using `.NET Core 2.0` cli tooling:
```
dotnet restore
dotnet build geometry3Sharp.csproj -c Release
```

Generating NuGet package:
```
dotnet pack geometry3Sharp.csproj -c Release
```

You can also easily add CI support using for example appveyor:

Example  of `appveyor.yml`:
```
version: '{build}'
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet restore

    dotnet build geometry3Sharp.csproj -c Release

    dotnet pack geometry3Sharp.csproj -c Release
test: off
artifacts:
- path: bin\Release\*.nupkg
deploy: off
```

Sample build: https://ci.appveyor.com/project/wieslawsoltes/geometry3sharp

### CODE REVIEW

**Comment by rms80** [comment]
sounds great! glad to have some help from someone who knows what they are doing =)

I have a few questions before I merge:
1) are you ok with these changes being released under boost license?
2) will this new csproj still work with vs2015? not a dealbreaker, just wondering if I should keep the old one around as well.

**Comment by wieslawsoltes** [comment]
1. Yes.
2. No. This is new project format. Requires VS2017,  latest mono or .NET Core 2.0. You can keep old project around if you want.

The binaries are compatible with older frameworks and VS2015. You can add additional targets like: `net20;net30;net35;net40;net46;net461;net462;net47` etc. if you want (if they support all api used)  in TargetFrameworks property. The new csproj  format is also human readable which is big plus. For more see https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

I have targeted `netstandard2.0` which does cover all api's (older versions do not support some api used like ArrayList  - this probably can be refactored to support older netstandard versions like `netstandard1.1` which would be most compatible but I do not use it in my projects anymore). Also I have targeted `net45`, your old project targeted `4.6` but it compiles with `net45`  which is more backward compatible.

**Comment by rms80** [comment]
This project file did not work for me after I merged. Updating to the latest version of VS2017 fixed the problem, but I don't think it is a good idea to require that of all users (for example many companies mandate specific VS versions, etc, and are rarely using the latest).

So, I moved this csproj to geometry3Sharp_netstandard.csproj. I am using this project for the appveyor build like you suggested, and working on publishing the nupkg...

**Comment by wieslawsoltes** [comment]
@rms80 Ok no problem. I am most interested in using this library via `NuGet` with `netstandard2.0` and `net45` support.

**Comment by rms80** [comment]
It is on nuget.org now: https://www.nuget.org/packages/geometry3Sharp

seems to work?

**Comment by wieslawsoltes** [comment]
Thanks! Will test later this weekend.

**Comment by wieslawsoltes** [comment]
@rms80 Tested the NuGet package and works great! Thank you for putting it on NuGet.

**Pull request merged**
