### PR TITLE
Add Polygon2d.Contains(Segment2d) method

### PR DESCRIPTION
**Pull request by gregmeess**

### CODE REVIEW

**Comment by gregmeess** [comment]
Currently, it looks like calling the method `Polygon2d.Intersects(Polygon2d o)` on a polygon completely contained within the other will return false as long as their perimeters don't cross; is this the intended behavior?

**Comment by rms80** [comment]
Yes, in many cases you do want to know about intersection vs containment (eg when sorting nested polygons into polygonal "solids", where some might also be overlapping). The polygons aren't really assumed to be "2d solids"  (although that would be a useful concept to have...)

**Comment by rms80** [comment]
Could you maybe triple-slash-comment the functions just to note the semantics (ie what counts as contained and intersecting)? Obviously I should be doing this too...

**Comment by gregmeess** [comment]
Alright, added comment strings!

Given the clarification on terminology, the new methods for `Contains(Segment2d)` don't seem consistent with the existing methods, but hopefully the comment strings will avoid confusion for now.

**Pull request merged**
